/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as InvitationInvitationIdRouteImport } from './routes/invitation.$invitationId'
import { Route as AuthedCallbackRouteImport } from './routes/_authed/callback'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedPeriodOverviewRouteRouteImport } from './routes/_authed/_period-overview/route'
import { Route as AuthedPeriodOverviewIndexRouteImport } from './routes/_authed/_period-overview/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedPeriodOverviewTransactionsRouteImport } from './routes/_authed/_period-overview/transactions'
import { Route as AuthedSettingsEspacesIndexRouteImport } from './routes/_authed/settings/espaces/index'
import { Route as AuthedSettingsCategoriesIndexRouteImport } from './routes/_authed/settings/categories/index'
import { Route as AuthedSettingsBanquesIndexRouteImport } from './routes/_authed/settings/banques/index'
import { Route as AuthedSettingsBanquesAjouterRouteImport } from './routes/_authed/settings/banques/ajouter'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationInvitationIdRoute = InvitationInvitationIdRouteImport.update({
  id: '/invitation/$invitationId',
  path: '/invitation/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCallbackRoute = AuthedCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPeriodOverviewRouteRoute =
  AuthedPeriodOverviewRouteRouteImport.update({
    id: '/_period-overview',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPeriodOverviewIndexRoute =
  AuthedPeriodOverviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPeriodOverviewRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPeriodOverviewTransactionsRoute =
  AuthedPeriodOverviewTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthedPeriodOverviewRouteRoute,
  } as any)
const AuthedSettingsEspacesIndexRoute =
  AuthedSettingsEspacesIndexRouteImport.update({
    id: '/espaces/',
    path: '/espaces/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsCategoriesIndexRoute =
  AuthedSettingsCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsBanquesIndexRoute =
  AuthedSettingsBanquesIndexRouteImport.update({
    id: '/banques/',
    path: '/banques/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsBanquesAjouterRoute =
  AuthedSettingsBanquesAjouterRouteImport.update({
    id: '/banques/ajouter',
    path: '/banques/ajouter',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/callback': typeof AuthedCallbackRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/transactions': typeof AuthedPeriodOverviewTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/': typeof AuthedPeriodOverviewIndexRoute
  '/settings/banques/ajouter': typeof AuthedSettingsBanquesAjouterRoute
  '/settings/banques': typeof AuthedSettingsBanquesIndexRoute
  '/settings/categories': typeof AuthedSettingsCategoriesIndexRoute
  '/settings/espaces': typeof AuthedSettingsEspacesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/callback': typeof AuthedCallbackRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/transactions': typeof AuthedPeriodOverviewTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/': typeof AuthedPeriodOverviewIndexRoute
  '/settings/banques/ajouter': typeof AuthedSettingsBanquesAjouterRoute
  '/settings/banques': typeof AuthedSettingsBanquesIndexRoute
  '/settings/categories': typeof AuthedSettingsCategoriesIndexRoute
  '/settings/espaces': typeof AuthedSettingsEspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_period-overview': typeof AuthedPeriodOverviewRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/callback': typeof AuthedCallbackRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/_authed/_period-overview/transactions': typeof AuthedPeriodOverviewTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/_period-overview/': typeof AuthedPeriodOverviewIndexRoute
  '/_authed/settings/banques/ajouter': typeof AuthedSettingsBanquesAjouterRoute
  '/_authed/settings/banques/': typeof AuthedSettingsBanquesIndexRoute
  '/_authed/settings/categories/': typeof AuthedSettingsCategoriesIndexRoute
  '/_authed/settings/espaces/': typeof AuthedSettingsEspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings'
    | '/callback'
    | '/invitation/$invitationId'
    | '/transactions'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/'
    | '/settings/banques/ajouter'
    | '/settings/banques'
    | '/settings/categories'
    | '/settings/espaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/callback'
    | '/invitation/$invitationId'
    | '/transactions'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/'
    | '/settings/banques/ajouter'
    | '/settings/banques'
    | '/settings/categories'
    | '/settings/espaces'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_period-overview'
    | '/_authed/settings'
    | '/_authed/callback'
    | '/invitation/$invitationId'
    | '/_authed/_period-overview/transactions'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/_period-overview/'
    | '/_authed/settings/banques/ajouter'
    | '/_authed/settings/banques/'
    | '/_authed/settings/categories/'
    | '/_authed/settings/espaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InvitationInvitationIdRoute: typeof InvitationInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$invitationId': {
      id: '/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/invitation/$invitationId'
      preLoaderRoute: typeof InvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/callback': {
      id: '/_authed/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthedCallbackRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_period-overview': {
      id: '/_authed/_period-overview'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedPeriodOverviewRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_period-overview/': {
      id: '/_authed/_period-overview/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedPeriodOverviewIndexRouteImport
      parentRoute: typeof AuthedPeriodOverviewRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_period-overview/transactions': {
      id: '/_authed/_period-overview/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedPeriodOverviewTransactionsRouteImport
      parentRoute: typeof AuthedPeriodOverviewRouteRoute
    }
    '/_authed/settings/espaces/': {
      id: '/_authed/settings/espaces/'
      path: '/espaces'
      fullPath: '/settings/espaces'
      preLoaderRoute: typeof AuthedSettingsEspacesIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/categories/': {
      id: '/_authed/settings/categories/'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthedSettingsCategoriesIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/banques/': {
      id: '/_authed/settings/banques/'
      path: '/banques'
      fullPath: '/settings/banques'
      preLoaderRoute: typeof AuthedSettingsBanquesIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/banques/ajouter': {
      id: '/_authed/settings/banques/ajouter'
      path: '/banques/ajouter'
      fullPath: '/settings/banques/ajouter'
      preLoaderRoute: typeof AuthedSettingsBanquesAjouterRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
  }
}

interface AuthedPeriodOverviewRouteRouteChildren {
  AuthedPeriodOverviewTransactionsRoute: typeof AuthedPeriodOverviewTransactionsRoute
  AuthedPeriodOverviewIndexRoute: typeof AuthedPeriodOverviewIndexRoute
}

const AuthedPeriodOverviewRouteRouteChildren: AuthedPeriodOverviewRouteRouteChildren =
  {
    AuthedPeriodOverviewTransactionsRoute:
      AuthedPeriodOverviewTransactionsRoute,
    AuthedPeriodOverviewIndexRoute: AuthedPeriodOverviewIndexRoute,
  }

const AuthedPeriodOverviewRouteRouteWithChildren =
  AuthedPeriodOverviewRouteRoute._addFileChildren(
    AuthedPeriodOverviewRouteRouteChildren,
  )

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsBanquesAjouterRoute: typeof AuthedSettingsBanquesAjouterRoute
  AuthedSettingsBanquesIndexRoute: typeof AuthedSettingsBanquesIndexRoute
  AuthedSettingsCategoriesIndexRoute: typeof AuthedSettingsCategoriesIndexRoute
  AuthedSettingsEspacesIndexRoute: typeof AuthedSettingsEspacesIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsBanquesAjouterRoute: AuthedSettingsBanquesAjouterRoute,
  AuthedSettingsBanquesIndexRoute: AuthedSettingsBanquesIndexRoute,
  AuthedSettingsCategoriesIndexRoute: AuthedSettingsCategoriesIndexRoute,
  AuthedSettingsEspacesIndexRoute: AuthedSettingsEspacesIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedPeriodOverviewRouteRoute: typeof AuthedPeriodOverviewRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedCallbackRoute: typeof AuthedCallbackRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedPeriodOverviewRouteRoute: AuthedPeriodOverviewRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedCallbackRoute: AuthedCallbackRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InvitationInvitationIdRoute: InvitationInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
