/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedCallbackRouteImport } from './routes/_authed/callback'
import { Route as AuthedRevueRouteImport } from './routes/_authed/_revue'
import { Route as AuthedCategoriesIndexRouteImport } from './routes/_authed/categories/index'
import { Route as AuthedBanquesIndexRouteImport } from './routes/_authed/banques/index'
import { Route as AuthedRevueIndexRouteImport } from './routes/_authed/_revue/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedBanquesAjouterRouteImport } from './routes/_authed/banques/ajouter'
import { Route as AuthedRevueTransactionsRouteImport } from './routes/_authed/_revue/transactions'
import { Route as AuthedRevueRevueEpureeRouteImport } from './routes/_authed/_revue/revue-epuree'
import { Route as AuthedRevueClasserRouteImport } from './routes/_authed/_revue/classer'
import { Route as AuthedRevueCategorieNameRouteImport } from './routes/_authed/_revue/categorie.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCallbackRoute = AuthedCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRevueRoute = AuthedRevueRouteImport.update({
  id: '/_revue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesIndexRoute = AuthedCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBanquesIndexRoute = AuthedBanquesIndexRouteImport.update({
  id: '/banques/',
  path: '/banques/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRevueIndexRoute = AuthedRevueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRevueRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBanquesAjouterRoute = AuthedBanquesAjouterRouteImport.update({
  id: '/banques/ajouter',
  path: '/banques/ajouter',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRevueTransactionsRoute = AuthedRevueTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRevueRoute,
} as any)
const AuthedRevueRevueEpureeRoute = AuthedRevueRevueEpureeRouteImport.update({
  id: '/revue-epuree',
  path: '/revue-epuree',
  getParentRoute: () => AuthedRevueRoute,
} as any)
const AuthedRevueClasserRoute = AuthedRevueClasserRouteImport.update({
  id: '/classer',
  path: '/classer',
  getParentRoute: () => AuthedRevueRoute,
} as any)
const AuthedRevueCategorieNameRoute =
  AuthedRevueCategorieNameRouteImport.update({
    id: '/categorie/$name',
    path: '/categorie/$name',
    getParentRoute: () => AuthedRevueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/callback': typeof AuthedCallbackRoute
  '/classer': typeof AuthedRevueClasserRoute
  '/revue-epuree': typeof AuthedRevueRevueEpureeRoute
  '/transactions': typeof AuthedRevueTransactionsRoute
  '/banques/ajouter': typeof AuthedBanquesAjouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/': typeof AuthedRevueIndexRoute
  '/banques': typeof AuthedBanquesIndexRoute
  '/categories': typeof AuthedCategoriesIndexRoute
  '/categorie/$name': typeof AuthedRevueCategorieNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/callback': typeof AuthedCallbackRoute
  '/classer': typeof AuthedRevueClasserRoute
  '/revue-epuree': typeof AuthedRevueRevueEpureeRoute
  '/transactions': typeof AuthedRevueTransactionsRoute
  '/banques/ajouter': typeof AuthedBanquesAjouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/': typeof AuthedRevueIndexRoute
  '/banques': typeof AuthedBanquesIndexRoute
  '/categories': typeof AuthedCategoriesIndexRoute
  '/categorie/$name': typeof AuthedRevueCategorieNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_revue': typeof AuthedRevueRouteWithChildren
  '/_authed/callback': typeof AuthedCallbackRoute
  '/_authed/_revue/classer': typeof AuthedRevueClasserRoute
  '/_authed/_revue/revue-epuree': typeof AuthedRevueRevueEpureeRoute
  '/_authed/_revue/transactions': typeof AuthedRevueTransactionsRoute
  '/_authed/banques/ajouter': typeof AuthedBanquesAjouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/_revue/': typeof AuthedRevueIndexRoute
  '/_authed/banques/': typeof AuthedBanquesIndexRoute
  '/_authed/categories/': typeof AuthedCategoriesIndexRoute
  '/_authed/_revue/categorie/$name': typeof AuthedRevueCategorieNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/callback'
    | '/classer'
    | '/revue-epuree'
    | '/transactions'
    | '/banques/ajouter'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/'
    | '/banques'
    | '/categories'
    | '/categorie/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/callback'
    | '/classer'
    | '/revue-epuree'
    | '/transactions'
    | '/banques/ajouter'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/'
    | '/banques'
    | '/categories'
    | '/categorie/$name'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_revue'
    | '/_authed/callback'
    | '/_authed/_revue/classer'
    | '/_authed/_revue/revue-epuree'
    | '/_authed/_revue/transactions'
    | '/_authed/banques/ajouter'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/_revue/'
    | '/_authed/banques/'
    | '/_authed/categories/'
    | '/_authed/_revue/categorie/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/callback': {
      id: '/_authed/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthedCallbackRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_revue': {
      id: '/_authed/_revue'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRevueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/': {
      id: '/_authed/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/banques/': {
      id: '/_authed/banques/'
      path: '/banques'
      fullPath: '/banques'
      preLoaderRoute: typeof AuthedBanquesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_revue/': {
      id: '/_authed/_revue/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedRevueIndexRouteImport
      parentRoute: typeof AuthedRevueRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/banques/ajouter': {
      id: '/_authed/banques/ajouter'
      path: '/banques/ajouter'
      fullPath: '/banques/ajouter'
      preLoaderRoute: typeof AuthedBanquesAjouterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_revue/transactions': {
      id: '/_authed/_revue/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedRevueTransactionsRouteImport
      parentRoute: typeof AuthedRevueRoute
    }
    '/_authed/_revue/revue-epuree': {
      id: '/_authed/_revue/revue-epuree'
      path: '/revue-epuree'
      fullPath: '/revue-epuree'
      preLoaderRoute: typeof AuthedRevueRevueEpureeRouteImport
      parentRoute: typeof AuthedRevueRoute
    }
    '/_authed/_revue/classer': {
      id: '/_authed/_revue/classer'
      path: '/classer'
      fullPath: '/classer'
      preLoaderRoute: typeof AuthedRevueClasserRouteImport
      parentRoute: typeof AuthedRevueRoute
    }
    '/_authed/_revue/categorie/$name': {
      id: '/_authed/_revue/categorie/$name'
      path: '/categorie/$name'
      fullPath: '/categorie/$name'
      preLoaderRoute: typeof AuthedRevueCategorieNameRouteImport
      parentRoute: typeof AuthedRevueRoute
    }
  }
}

interface AuthedRevueRouteChildren {
  AuthedRevueClasserRoute: typeof AuthedRevueClasserRoute
  AuthedRevueRevueEpureeRoute: typeof AuthedRevueRevueEpureeRoute
  AuthedRevueTransactionsRoute: typeof AuthedRevueTransactionsRoute
  AuthedRevueIndexRoute: typeof AuthedRevueIndexRoute
  AuthedRevueCategorieNameRoute: typeof AuthedRevueCategorieNameRoute
}

const AuthedRevueRouteChildren: AuthedRevueRouteChildren = {
  AuthedRevueClasserRoute: AuthedRevueClasserRoute,
  AuthedRevueRevueEpureeRoute: AuthedRevueRevueEpureeRoute,
  AuthedRevueTransactionsRoute: AuthedRevueTransactionsRoute,
  AuthedRevueIndexRoute: AuthedRevueIndexRoute,
  AuthedRevueCategorieNameRoute: AuthedRevueCategorieNameRoute,
}

const AuthedRevueRouteWithChildren = AuthedRevueRoute._addFileChildren(
  AuthedRevueRouteChildren,
)

interface AuthedRouteChildren {
  AuthedRevueRoute: typeof AuthedRevueRouteWithChildren
  AuthedCallbackRoute: typeof AuthedCallbackRoute
  AuthedBanquesAjouterRoute: typeof AuthedBanquesAjouterRoute
  AuthedBanquesIndexRoute: typeof AuthedBanquesIndexRoute
  AuthedCategoriesIndexRoute: typeof AuthedCategoriesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedRevueRoute: AuthedRevueRouteWithChildren,
  AuthedCallbackRoute: AuthedCallbackRoute,
  AuthedBanquesAjouterRoute: AuthedBanquesAjouterRoute,
  AuthedBanquesIndexRoute: AuthedBanquesIndexRoute,
  AuthedCategoriesIndexRoute: AuthedCategoriesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
